version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  kittygram_backend:
    image: thechizhman/kittygram_final
    env_file: .env
    volumes:
      - media:/media
      - static_volume:/backend_static
    depends_on:
      - db
  kittygram_frontend:
    image: thechizhman/kittygram_final
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: thechizhman/kittygram_final
    env_file: .env
    volumes:
      - static_volume:/static/
      - media:/media/
    ports:
      - 9000:80